"""The written reports in results/: BACKTEST.md (the eight measures plus five campaigns up close) and
VALIDATION.md. Every number is computed; nothing is typed in."""
from .backtest import summarise
from .config import NAME, TIERS


def _rs(x):
    return f"₹{x:,.0f}"


def _pct(x):
    return "–" if x is None else f"{x:.0%}"


def _cpm(x):
    return "–" if x is None else f"₹{x:,.1f}"


def pick_showcase(rows, n=5):
    """Recent campaigns covering different categories and platforms, with enough posts to read."""
    chosen, seen = [], set()
    for c, o, w in sorted(rows, key=lambda r: r[0]["start_date"], reverse=True):
        key = (c["category"], c["platform"])
        if key in seen or len(w["posts"]) < 8:
            continue
        chosen.append((c, o, w))
        seen.add(key)
        if len(chosen) == n:
            break
    return sorted(chosen, key=lambda r: r[0]["start_date"])


def backtest_md(world, rows):
    b = summarise(rows)
    t = b["creators_paid_by_tier"]
    ret = b["returned"]
    lines = [
        "# Backtest", "",
        f"Generated by `python -m ladder backtest` from the world made by recipe seed {world.recipe.seed} "
        f"({len(world.campaigns)} campaigns, {len(world.creators)} creators, {len(world.posts)} posts). "
        "Every past campaign is paid twice on the same posts: the old way (its own gut-feel ladder, the same "
        f"for everyone, no fraud check, no budget stop) and by {NAME} (rungs, reference and fraud cut-offs "
        "built only from campaigns that had ended before it started). Creator behaviour is held fixed.", "",
        "## Eight measures", "",
        "| | Old way | " + NAME + " |", "|---|---:|---:|",
        f"| Campaigns over budget | {b['budget']['old_over']} of {b['campaigns']} | {b['budget']['new_over']} |",
        f"| Worst overspend | {b['budget']['old_worst']:.1f}× budget | {b['budget']['new_worst']:.2f}× (never over) |",
        f"| Cost per 1,000 genuine views (median) | {_cpm(b['cost_per_1k']['old'])} | {_cpm(b['cost_per_1k']['new'])} |",
        f"| Money returned / left unspent | {_rs(ret['old_unspent'])} left unspent | {_rs(ret['new_thin'])} thin-market refunds + {_rs(ret['new_between_rungs'])} between rungs |",
        f"| Paid for bought views | {_rs(b['bought']['old'])} | {_rs(b['bought']['new'])} ({_rs(b['bought']['blocked'])} caught and never paid) |",
    ]
    lines += [f"| Creators paid, {tier} | {_pct(t['old'][tier]['rate'])} | {_pct(t['new'][tier]['rate'])} |" for tier in TIERS]
    lines += [
        f"| Fair Reach rescues | – | {b['fair_reach']['campaigns']} campaigns, {b['fair_reach']['creators']} creators paid only because of it |",
        f"| Price swing between similar campaigns (CV, lower is steadier) | {b['price_stability']['old']:.2f} | {b['price_stability']['new']:.2f} |",
        f"| Pay to the top 10% of creators | {_pct(b['concentration']['old'])} | {_pct(b['concentration']['new'])} |",
        "", "Pay concentration is higher with " + NAME + " because pay follows reach, and reach is concentrated. "
        "The old way's flat payouts capped what the biggest posts earned.", "",
        "## Five campaigns up close", "",
    ]
    for c, o, w in pick_showcase(rows):
        creators = lambda res: {d["creator_id"] for d in res["posts"]}
        paid = lambda res: {d["creator_id"] for d in res["posts"] if d["paid"] > 0}
        seg = max(w["rungs"], key=lambda s: sum(1 for d in w["posts"] if "|".join((d["category"], d["platform"], d["tier"], d["format"])) == s))
        lines += [
            f"### {c['campaign_id']} · {c['category']} · {c['platform']} · budget {_rs(c['total_budget'])}", "",
            "| | Old way | " + NAME + " |", "|---|---:|---:|",
            f"| Paid | {_rs(o['paid'])} ({o['paid'] / c['total_budget']:.0%} of budget) | {_rs(w['paid'])} ({w['paid'] / c['total_budget']:.0%}) |",
            f"| Over budget | {_rs(o['over_budget'])} | {_rs(0)} |",
            f"| Money back | – | {_rs(w['refund'])} |",
            f"| Per 1,000 genuine views | {_cpm(1000 * o['paid'] / o['genuine_views']) if o['genuine_views'] else '–'} | {_cpm(1000 * w['paid'] / w['genuine_views']) if w['genuine_views'] else '–'} |",
            f"| Creators paid | {len(paid(o))} of {len(creators(o))} | {len(paid(w))} of {len(creators(w))} |",
            f"| Paid for bought views | {_rs(o['paid_for_bought'])} | {_rs(sum(d['paid'] for d in w['posts'] if d['bought'] and not d['fraud']))} |",
            "",
            "Old ladder (same for everyone): " + ", ".join(f"{v:,} views → ₹{p:,}" for v, p in world.ladder_by_campaign[c['campaign_id']]),
            "",
            f"{NAME} rungs for its biggest group ({seg.replace('|', ' · ')}), in views = coins: "
            + ", ".join(f"{v:,}" for v in (w['rungs'][seg] or [])) + f". Settled {w['regime']} at "
            + f"₹{1000 * w['price']:,.1f} per 1,000 coins.", "",
        ]
    return "\n".join(lines)


def validation_md(world, v):
    r = v["rungs"]
    lines = [
        "# Validation", "", f"World from recipe seed {world.recipe.seed}. All computed by `python -m ladder validate`.", "",
        "## Is the generated world realistic?", "",
        f"- **Heavy tails:** the top 10% of posts carry {v['heavy_tail']['top_10pct_share']:.0%} of views; the "
        f"99th-percentile post has {v['heavy_tail']['p99_over_median']:.0f}× the median's views.",
        f"- **Growth shapes:** {v['growth']['peak_on_first_day']:.0%} of posts peak on day one, "
        f"{v['growth']['peak_after_day_3']:.0%} after day 3; {v['growth']['stopped_by_end']:.0%} have stopped by the campaign's end.",
        f"- **Bigger accounts get more views:** correlation of log followers and log views = {v['followers_vs_views_correlation']:.2f}.",
        "", "## Does the method keep its promises?", "",
        "| Rung | Designed reach | Actual reach on campaigns it wasn't built from |", "|---:|---:|---:|",
    ]
    lines += [f"| {i + 1} | {d:.0%} | {a:.0%} |" for i, (d, a) in enumerate(zip(r["design"], r["actual"] or []))]
    f = v["fraud"]
    lines += ["", f"**Fraud check:** {f['caught']} of {f['bought_posts']} posts with bought views held ({_pct(f['catch_rate'])}); "
              f"{f['genuine_held']} of {f['genuine_posts']} genuine posts held ({f['false_alarm_rate']:.1%}). "
              "What slips through was dripped in slowly to look organic: the known limit.", ""]
    return "\n".join(lines)
